### ISSUE TITLE
saving JS files does a weird thing with the Chrome tab

### ISSUE THREAD

**Issue by andrewljohnson** [andrewljohnson/deckzap#58]
@nathancahill are you able to reproduce this?

When I edit/save a JS file, it used to automatically reload the Chrome tab. Now when it reloads the tab, it paints another copy of the UI below the old one, down the page, so you end up with the old UX on top and the updated UX below.

**Comment by nathancahill** [comment]
Fixed this by adding this code: https://github.com/parcel-bundler/parcel/issues/1915#issuecomment-414747704
