### ISSUE TITLE
create_card works in dev, not in prod

### ISSUE THREAD

**Issue by andrewljohnson** [andrewljohnson/deckzap#59]
@nathancahill could you look into this and maybe LMK how you debug serverside issues like this now?

I don't see anything in JS console.

http://deckzap.com/create_card/

**Comment by nathancahill** [comment]
It looks like the custom cards get wiped when Django runs `collectstatic` so it's probably best to commit the svgs in `card-art-custom` to the repo.

**Comment by andrewljohnson** [comment]
Hmm, I guess I don't really object to checking these in. But...

1. I think this line will fail on a fresh install because the source and destination files will be the same: https://github.com/andrewljohnson/deckzap/blob/main/create_cards/migrations/0002_auto_20211113_0331.py#L27

    https://www.geeksforgeeks.org/python-shutil-copy2-method/

2. It seems less clean than having the initial install pipeline start from the bundle I sourced from https://game-icons.net/

Should we tweak the migrations so this doesn't fail, or is there a straightforward way to avoid collectstatic wiping out the files? I guess I don't understand why collectstatic would kill them?

**Comment by nathancahill** [comment]
This is fixed with the svgs committed in the repo now.
